#Input:


s = "AAAB"
k = 0
s = "ABAA"
k = 0
s = "AAAA"
k = 2


s = "AAAA"
k = 2
s = "AABABBA"
k = 1



s = "AAAB"
k = 0

s = "ABAA"
k = 0

#Output:
#4





s = "ABAB"
k = 2

s = "AABABBA"
k = 1

s = "ABCDE"
k = 1

s = "ABBB"
k = 1

s = "WBRIQCVFYHTSFAJVVSUBLQYBSMUWULUKUAMUSDTVJRWSSYRXTSCIYUDTGOCWRJHBURWQYENEEYVCHVIKBYBQJUGRWVLFORNVSISGDNZREMWMUWXWWRMPBNZAPSFDSGVCGJPEDUCWBMGEZCWUVNKFTFONIKHWGYPFGMEIKMYFRVDDTPEZLUHZIHVKBWGMUUDYBTXZCIRVOAWZTSEZUTJNDXJSWXZZTXPNTCNDPPWLXEHJPZVKAYMHYDNQRMIPEIRJNGYZQCIQSWRQSLSFENBTEABYWJIQNDMQHXMWALFKQBFWWNKSVDIZHLSAQWEQKHFFOUECQVUDMYNFUYBMROIGKLKPYIWSBBORHGLQOTJSOOIABZAJVPDUHHHUIXQBCWVSMVGSOGDVDILBJEFNIPSNNODGTWFHCPYBETOEYXEUDHGJDYMUAXLSIHDCDBVZUWFOMKOJGWTXEPOSTTUXJATSJJACDQYBLWNWOAGZQEQQZKVEKMMYARXHQXRLNAUMPDFSCODEFPFVKIJRYFYNBNRAXGDIEWDPVCRPQRZKWUKKSGFHIVFVHSUEYALRENJVBEQINQASMBRXLRPKXNHCZRVMVSOSJDRJHZIWMCLOTKNYVTRDPNUEJLMIAHFLLWUQLUZQVDUBRAHJOFSSAMOJOAYLKEGCJGTRKHHRZJTTBLGCUMLTKILXNYOTGZQWCKOJLLVTGSSRHDPPRLMXFNILNJPHMIWJKKHJNJRLQTVFKBKAJZMDVTXPGXHOONEYUXVILSEGSJKHLHCFGCAZMWYXFUMNWHIYGZFRZPRJTVBEXCFFGULMZSDRZAVWUVDQCTXZBHFAPOZQCRKVHWWYEALJBYDGMIEEXDDFZYEBUHUEZMZALGZAHHAECPMEGDRMVZZNQRQULRNRABQUOIEGXLNOZUFQJKDKGCZFVIPBIRNQBEERWMTWUBIGFUHKRQVACWPGFHFAPFBZMQXEYGWRBWZEQEHXXCUAJWEECFNHXRWFQUPMOQEEZWRPRHILZVCCWDTFZETWABPEKWCBDIHEAZKVNQOOOGQVGHTTUFCAFWHMECOSZKTHQXPORBGXLVDETCBIDIOYSZNPOXUKHSFBLSWVBXQOPFSTLVQPSIKKGUFCDCKVBSMAAEGUDFUXJAFQYVVTKEEQUUXJQMSGXGWEUELFFFVEHRDPZKBVNUQZOTMXIZFXCURFDSWINGWIAPLHLXZDOMNMMSYNNKAFNGLVOBYERFMSGLNNFDXWGHKADQVLIQHITXFBYTORPZYBWQEBNTCETQHVLMCHDHNQEUQWLCGDKXUHSQIILMHVFQIJMWSEXTLNRWMRDUAEEHNYTCWKWIGRASCAVRBSZEYHJXXWQAILZXHZQNOEUQIYPGXRRMCAFBOPTQFJIDWUUIMTBESCAJYMPDJGPGHFEXLPGJLDJIWMROJISDHZUYOMWQEWYTPHDMYYUKZWZFIGOACLZVYMKTMAHHGNHRMFBLPDWUPVZXHJPJAAFYFGMSRSQKWXKOWMPNTZPUBYJYIPMRERSTWHEDSXXJGHHMWYRNBEGYVHUQVVELAORPJWLECIKPPPNTGCJFBJNZGXCCTUNOJMZLXDTIWDDHBMBXXUUMWNJSNPVPKKEDWRPIATEAVHFONBVYVWCSIYPKFCIIMXKPYWKCXLQGKQNXDKKHGSTIWAMGDLXJCYFQNOLKVRPBUMNTQYZHACFZFGGWQIJRSAVKDXHHKQODGBEBFLPIESJEQQFXOVXORDPREKPDHMYSXAQCSSBPIQTFJCDRDOFQUHHHJKIRAPJACSFWVUBDJMQBJFNFFXXSLOBJFTMBBILIBFQOUMCQXMQHXNICXDXYKXEAAHVYSUHAYQKEPLQXVJYFFNWZRXXVWUNTQGWYURBJIHTSPIMCVHXIQIGQZJAVNYIFRYNPNYMQNYBQIGFOYGHOZBBHDYQMSYPSMAXZOWMAGWVXDAXNCTBRLQPOTRSPUHWSXLJVRKRCBZRAYWZHAFZXONWTMNQDDYVZAPOPHUHOJGRSHBJLXLTOMRGJLZDBVTKIWJHAQXFXAZSANBVQCIYPLBSSYULGOARKRKDSHSWOYCAEQGWEZQXWHTWSHGVOBBKAYBUMJORLVAPLQZYVFIGREYEUGUHDJYCLVXFBURBPFRSFOISPTCTRFULTBZPBZNWRRWJXSYYEAAKCRNGNFWSZDFTUIZVNVYPDMGXATHULMMSLQQHYTWOOTIFJIERABJPAUQAQVFUBGIHJTBIVAFNALLKKGRCNIONHOATUZNROWTRJCYVYLCWCPDUQEBTERIBDARVZPQJBUUJOAIYPYIUWXFCAQOLEMWVEMUWXGSOZJRAAAUVDCODWQONAEBQKNPAPCBHCNQAVRCNOBWSPCKVSUQHHNWGUTIHUDCEKMLHOCWHMKPYBGTQYKXSSIAMBMKLWZMGQLNAMAUDKQZTNUTZJWBBQUTWAUQMQMXTJHERZGYIAOGHALPDUUXVAQJFTDWVLJAHDNGGHDELGPNUYJKGLFNUFVQOKXNDDIMLEWHOKPKLWSGTHBDQGQQIVTRKNSSLPVCQPGWZPLKMWTPWOMWCKLFKHDDOBOUQVHJENRGVJBNCJVJDQYEDBSVOEXPJVYYWIMVXLXAEVFHURSJIMNJQGVDSMREMQGOKXAFWMMFGSMZBIVGIOHWKCHYPDRQEUDFBDKQFQPOEILESIULDPSKYYOJYIQCKPZSIBPNQIZCWJHCUZSEJOXWGUKXPAWXJPSFFDPANHLEAXAUMOTOZTCNBSBPGLJSWJATQFOJTNGPCSGXOFYCSKBLALTPNVODVZSDLIYACERBYLACMDIESPMTFVBWGSYDOZXTTKVWXWGWBGAGNQLZNWWJFOTJRAOKHGRUTKFLRYUGOMHRSITXDJRSCRCDDRWKGVVXAUGPUUOPGSVXQSYAIUAQAKMZHRFHZZDTHRTRMFPGIWCZLSRIILSRMBRFSEMAVGLYVUAWQQCTEDUZDHCSMLUGDUVKUTPMIBYDEPNVPWUIZAZKEMOGRMLSITHOUYBZBJWTMYBXLETPBIXCJQFIPVXOPKEEVNTJFVTYUGBDQJGTQFKNNEFIPUTITZRJBEMQZEPISAZBYFIMKKOWFMTRMTJTWVWPLYOXSKJDZUXAATGIOZDLCPJEGPUTBYAHJGLTZTOSRZZPQGNUWPUBFYGSDVSSYKZEOGJZMFUYBFDPORSJEGZTDVURPTMMQNMNQVFHIDMPGVKQKZKXVDMAJXOGXAOJJNXSNEOBEWUXGWNLTXZZPFRJYQNJICGDEFDIUOGWAOVTAGXNDVJRPHMZOKRZYMMNFAXYPTYZXITXADXDGVHEBEACVLPSOTAMLIVPHCSJWQKTSTCYKWETJDOYBXCHWCLGLBUTEHTRIPFTSYTMHHMXJBLFMLMIDDBGAZWSKFTIBDOUHOYYKTRKKVDFTSMTJWAHYEICILPFUDZEYFZLFWDZIXFORJCJJDLSDDOKNXTNIJHBDYFPTMGOGNJQJHNJTOXGVYBMVPZIUCANUODRIFUDWRZFSMZVHECLCHBVQWZSGOETPZHTPEYIYGDKERGBQMTTBAJVEIECMORZBWAOOVNTINTZIFPDOVSCFMUAGNGLVRZMUAHNEAFJNVPJUJWNENIMZMHQLXQTHDKZFTNISFGTNFNPKRDPBOEVPVNMRXRIQYZIBFAPMOHWOEXIEHSKABDTZDLBXCJJLZILVJBJCJGFPGBFZFNXDBUJWYSNYAUEQXTRDGUUKPHFKGQFNZUNWMIMJMROSPRZZIFVELXRWDZMDMYCDQEJYVZULVZCDPZGTPBFQORXGFPSOKMCHWMCLKOVPTRUBWETSPSBZKVREMQEIPTNQICTASVIHWROEZJNCFIQKBFNNABJGKWCSSBYMBOIKCADMOTWDBWAGXFDPMCLUURSQMMCVLBJZQAYUWNDYWBRAMSRPURRGVONEZTXELXJMASHSOBZLAUYEVIZIZJZPESNTIQTYVNGPRMHYCZWCMCYPXOBTZNWQRQDLUTNBDETJOBEWTEBMYAMYAEGNTNFHIWWRWQDUNMWUAFWOEDCINRXUIVPTODPGGEONSTXWEGEVBBLPFXVREHNNZQYLBRPNHHPUYSUTYOJHGKKQGSYPAUUUUHKSQHSUTZPHBTJSEQGLWSEADAGNQLIQDWVRMPHURXWPAOTIXMZFMSUCDZRJBNAGETGZSLYZHNORVSEFXGICAUUGKFNOIFPHVFZXZFZOANUBNGGUXUWZLVHWXLOLYCQNXODAWOAPTHZKKGSJAGYRYXEEAHDOYDOZUKSYKABDBGYPNLKOUGJWCVBDRNXWTCMUVKKGGABIJWVBEGNNWJHFURDMERBRNYCMZGLLHJRBBYOTQWAEBFQSWZLPEYUZJVGVHJZJMRTKUKAOWHUWBZLKKPEMMDXHCKTXMENLLNCQOEIDFAWRSBVNZDKDFFPRBYKTAOVQEMBVPANILXCHYOEEFQBEYXBWAGEUWHBQLAPIDBAYGXYWVYXWVPUIAJLMFUTWDNEQHYXCVPFADXNIIBQOKRYVTFXMNVGPOUKRXYILSCNLCTHCSENDXOIGWMTDPIUUAVDGSBQNDSVMYLSCTMRCMPBHNXWQIGCLKUFKRACWGDGJKOGRTTGWLCIXIZCFXSQPYQMQMPTDRTIFMTARDUFSRWCOCDUSMMVEESFBBFFRUMGBQYWWMFSIMIIXIDVHQWVDPHFNPUWDTCKUMOGAZNYZOBKRYZJTLTRHHJATNWYKYCEXIUTOFUOZOXUDUEYBMNQTMUZFCXIFZFMFVBVYCXONJJIBHHFSYRGLCKDPRGXGDHMATIATDGTPUPAINPKUHAHOWDCUNUBPQSNXPCJMBJTYPCOIJGCLZLJUAEDREFQBITUYJUFPCKWZNFKZRKHCETYLLBJDIVDAHWXEQQUFFCXYHYGELIPSUACOOKWCVURYTDSXBAKXZOKDHYJPLCUDTEFSCOCYNSGKIYRZENWBHTSRFFCEMSBOULZKYIDIFESVYXDXFGLYHDELFYBRTNXJTVUIVRMUXSCGHBWUKDEXYMMOHZAHQPPMCDOQBBMGYUNKWCIIJQHXYOCFEOHUPHSJKSWREATFCCUOPJNWMKASCSCPVVNLGGWCCFDQCHZKFIXBTEZOWAVXGRWPSCKBBETMEWGIIKCGPBZCERTRRNJZKCPRCJMWQCSSUYTKUZVFZMUBFLEPXXIYVVVOGINRQWKCMZYEFUTVBXUWNCZETLLFPUIWORGRLZFJMVUNEVVLMHEDDGKSYTYLGGRKVKHPADATKKLLTAOVGZPCDPCXDCGDQJMOMLOTIIRXEPRYXCPMNAWYFXUSHOKDPAVCENBNPUYKZJAGVRJZQFUMSFBTIRFSVYWLXSYWDFEAIQINEOWJUGBQBETPGMQZZODIDQOWNHUYURZELEFVSBPLZGFPVMNDUSBGEJOIXLEXBWHNKVAMWMLXDTZWYFZVLNGSEROQXOYZXCVJOWYBXZSKHELNDMXMHIBFUVBBEBIEPSPQFBKQUSGUAUDFCSBYLFYIUXREKIGCYYFBCDBRZECNDZGRDWAIDKSMCULRNIICFJFDJGNXVLMCTKIXQXPVAWFKXHSTFRUXMQLPVMEEKFKGVBXDIIMPDRUXQABVVKNQWENPTUYYCJOZXGFXJEZOYUJCNGHRTBPWPRFRFVQJLHKEHIYZXNOHZPVYSGNYAYFGWGHWCCYCDJZKUWKXQNTRTXFZKNPYTDAZBWQAPCZYGEOCLFGLFUZQMIMZAHYSXTPZIXSMNHDARHYKZAQCGUJVGFBVAIDNDUDEWPXJOLMOAHCLIKHFRGXHYOWOAMRQQMEIBNBYHWLTWAVNJINTXZHZEDHKTKGCIAFPWKWEKVGVKFEUBBGLETIRMBHJQMSUSGDISPGRJUTKGFWXOBPGBKAWCWUAVLIMYHFHMAPLGZRAOIWYZPXDQBVKPJISNNRFVOTANRCWCZGKFSVFKDNQOZAASPGVYTGIPRDEBOICEPVHJRCSPDPDHRTYZNOCUGDAWFSQRAOLYSQIXTGFXBXRVXMJFSNFYHEXWPHUCVMIZLNWDJQLVEFFDERMJVQCYDQKJGFUCQWAWXNUQNHXGVRVCUAQWRUNHEDQSSNXAPDVGRDSGIGYOGAMBQRZYIQGZLEDEYVUAUSACPIHDEDCTDTLDNNPJINTUSFGJJDRUQQZLWAQQSKHVJGMMMOTCXPNCOACRUBIQHCUKEFIPXIRENGDRSCMNGVHSYPIHJZKINCCVZTJTANUTWCDYSRGRENFBPPTSAMODACIIVDWDLEPCCPLJWATIFYBACOWGRWOUTQMOCSSVTWWIRULRYBGRTFFTALWPWVPABLNAGMSCPQGTZFTUWYYIVNOFFXADEHCFWCBSODYRJVQJFFBTASEGNOMJQSMBJMHJNJWUVLKDXYPEDJQMLWTWFIZZOMLBXHVZZFHTBMYRWSHKLKWAMDGBNCXGIIJVEQCDHAQCGWFPEKJCNYNHYRFTYNWQFCAHOZPOUFKYPHXBLRMLGOXVTKPXZDZCSZJCXDARCWOILEGCKECAXCLHIUSSZQLYQIWLJDWNTBESSPRERZFYWJNPOTDNIYPDEEVMCMPFQTRLRQHHDKAQBOSKAVTVBFHPPWSTISSGSZAXISHMSPPAYFMBYVYISQYITBVETPZWLBOQGAYBTTLBDCPHKDMYBTKNDTQXTWUGAUDUCZMWNUVZTSLIZNTWTNUTTXAFWQEBWDZGOSFSAABHFBFJUFLRSPARIBYYCGMDQJKUVHDUUFKITOCZEDWJBXDQXZVIYCFBRAJLULUZHCDEYHCUSECNCXOOFQQACSAIPTEALOFYMGCEOUBHAUCRIUTORHGSGZPOGRQUYHOICISUYZGCELDXWZAGEZIQTFSEVQVNDCHZLZEXLQLTPYBJRTLICGNDNHMOGZEWUVGKISEBAMCLBROJTIJZYZNTWCNOICNVJQVSDFOJUUSXYJVNXSKXGVJBHSVGDBVEHNAHAJHAWELALMILSOOAEKIZGMGRWSLAXNJXVNGLYJXROTKCGSYKYTEVZQMWEODRIBZIYXOPAZSUVIGWVDJIZWVDSYHLMDVFJSDQVNDXRMRUSEDMXAOUISQMGDBRRYCUQRORXNJYDZFLSKKDZDEQFRHBWFWOOQLYCFNETIVSZXPOUKPSJHAONOZDRNZAXUCTJOQNZDCMIXAOEOSDLRJYGJDIFGHROUFRLLDFEUVWNFHVTQRKKTMDLYDWCQWJLTXEZESVSWVAZLRPBNVMZQSLXLKSVZYVXHJBRNHGPTKSKRBMCISUTEFANPSEGMXNADBCHHBAOEVAKCPBMVGNXFAAECTFHJAVBEDXBTOLYFJLYKUOMYQNULMKTHMPPFOZWGUKFSILCIAYQVAYHOWXHGEDVZVIBQCBWHEJSYTDNZTEMAEDCPQIFDYUVCCBMYDMJGMTCLZGZHPWUHBETDKRIZGLXWALAJYDHUWBEIWFBQROYBDURARYHHNRHWGTMYCRUQBXYTIBTEUEJABMZWOTRTCHYXPECVYYXSZYVYPQNJRVZQUZFRBXTSWDNKAWXCRKHAZJJBNXOXLFFCLUEHTEWODGFPUQFWAGYLWLOTPGDTUVNSMQVKDFHXOZBCTIAEMNNYVJFEHZZYGKIRKKTTONQCOIBIRHUTNOBPTYENHOLPHIOVZARNHWSEORDMSIWOVBVPYFONLHBXGALLRZXWXINEMZZEUJGKCCEZLDGWOMDHSPNAZWJQZOMFWXCKFVJPQBNTAOZHCNZRABGHSEAYZYCINTCAAAJGWZGCPMPHFAMAXNYQCZWZCWLMXQFBMCJBYADMXWEUOUCKYOTLRFNQVYKSMDHYLZEEZHRIHRZUEEYAJOTWHZXHMPRXEDUXRPPHPMDMQBQXPEVLROIROKQRMUIFKQSBOGJYEXHVVJZOXMZDFOMNXDFXNVQLTCFBZSXXFMYKBJIRWARAIDUPBQDTONDXWSQYJFKIUWBVXHLNSYHGUPFQUXSOLWINNQWIRAZTPNIYAVEYURVKJFGEQMAHIEOKURMKTUZJQBSEOXWAUEMAQHYBNKUSJIDWBCKTVRJWOCLGCAZQMRDDULHNVFNGTHXRVEQWITQSMRGQIXXKBMFDISJSTMWVWDOSPZTRLLBBVCFQQTBSOPVTTNQZAJIOQBFUHJYBVSVFUQFBOVAFEIBOZOEXGRRJNLKOACELFOVLSEVWDOUSSOQABDVWLWWYWVYUVUXAXNOWQANTHVPVKPTYJJFRKANKBZEAIWZWBUDNTCYWVPKVSNUSVXBYOCERVSKBUVWUQWWBLSUQQBAPMQMEOTYFMSZVXLULKLOVMXTOUIMJPZPGVHSIQJTVCZTZXKQIEJQFUCTCYDXCUBESNPORTEOJFZXBRPQXDOYNCOIURIIWDCTKUSQASKWTZOMQANDJBZOGXXHWAZCYWIFWLGTWSSZXQDPYPSXSCYZRQYOMXCOILKCRQHWZDMTZJTFVKTIDYFZAJXBGGHLIPBJGFJHACPKYJPREOAWUFEQBVXDRHQIODBUNGBNXRSQKBVBRSEIEIWJYSPONGMMVQEBCFTQSLLYLISQMIYZOAJXMYEZXRERTERTTQUHMAVSMYHJEQIOMQUPURFIXBEOUURZUOOSFTXMHYSWDCHJYCRWDCAOQJZJRZAADMWELZPTCVBARAWWGLCVNEKHYPLEIYLKUWDBCZJQSKXHKPENTGTFNFOCRHVGZJZHNQOWOLLBRFJHDZYGRPGZANASIFVKCFSJEXZFPRMREAZTAVOARLLWSLGMZWWKPTCFOMGYMGIAGAPBTYTXFKVQJAAPBWIUASJBAHJNHWVTAXQGILJFTXRVHHJPVGHUZTZMWRRBIWVKRMVCRGITGLNDRIFYXZKZZFLNIHMSPUMZOJKWHIGIUFICOEPGJGUFKLZUKCFCJXWJCGDBSXZPOAWUZVPWTFSWXVSSNJBXGIMIHZINBXCMYRVWPGOJZQNCJFYXDEXZXNJVTWFQUYMSGHKJIUTDGGZXJSTGTIGQTRZIOJYVQUJSITSWNZJIFJUNIVICLIVYUPRXFDCSNCVJRDSPDEHENYUIGJEAJPXGWXRUNLVKWEJDIFDFFQFKXCIJPINAITZAOYWPEMGHVXQSZHIIEHITDXNUGGSRNSDKUAWKCMCZKELGSGUKHLNYOIVFHIWEHRAPAICWOCISZJFTGRGOWGYHUCYFCKAXVLYPITZCDPOUUYQJAITVGAGIZBZSTQNKYXOACVLJLYLYIQYDNFREMCZKYJPEBQFCRDWLICVLASTPKGHMZANJQZCLTUBZHXBLVRTZMZXTCTOZMEDAGFFQCQEBMQRNZLBWAMUNSEDOSKEIZEJGRXUHZZMXATUSWYYSFPLMJPUCGYNBOTDQJYGEQIGACCWVKTEMMJTAJPPYUADNPFJDEXJUIPJNFMMVVWWKTYBMRQCHWDKQDCVLZGNQDLTSKPUIISUITUGVYLAICSTYTACZGEDQBRBCPMDGGOWOCLVKKXMPWYXGJVIUSQSSGXXXKPLUDIUAOWTAZKKXDHIPZZUPRUKKLISDKHVLALASKSQVZYZFMVVFJSZXFSOQCJSZOLIGDCNOVWBIRWRQJEIRBBMEOTUCTTRIVUPZJRIJKIEWQOSRHHCBLQMWGQFSOSECYMOWRDKJNHXXWMJPWLLOGGVVVBPRNCQLIPUHRIKLONOZGSNDBAYRTQZGQFWFPVTZMAYRXOIJKXHEKRWDKDUMHRTZSKDYGIMIZTPHDQSJDFXCKANKZUBUBQZZPZTXDIIDDMKVVRQRVMYGTJLXLQDQNONJWWGOLGHGQHQTRZBVCYJGEFVKRJIYZOCZVCIAQFOAULOOQBDTGHICGFMNDCJGTQJFEEFDBSZOCZTZKYHAEZSYULKROMYLRWOKGNRQSKJGPTJFLZRZSUTVYOOIURSSFMOKANMTFGDZLJLLYZFXUNQAURHOPAJOZECXAMDZNCFFNVEDXGTZHNUJYORTYBXZRILGCSJMJAOFFSFTNNXXJUMXJZCBNPYZKECAKRFHDKZYPDAWR"
k = 2666
class Solution:
    def characterReplacement(self, s: str, k: int) -> int:
        print(len(s))
        if (len(s) == 0):
            return 0
        repeat_char = s[0]
        maximum_distance = 0
        start = 0
        i = 0

        if(k==0):
            for i_s in range(len(s)):

                if(i_s == start):
                    continue
                if(s[i_s] != repeat_char or len(s)-1 == i_s):
                    if(s[i_s] == repeat_char and len(s)-1 == i_s):
                        maximum_distance = max(maximum_distance, i_s+1 - start)
                    else:
                        maximum_distance = max(maximum_distance, i_s - start)
                    start = i_s
                    repeat_char = s[i_s]

            return maximum_distance
        else:
            for i_s in range(len(s)):

                if(i_s == start):
                    continue
                if (s[i_s] != repeat_char or len(s) - 1 == i_s):
                    temp_i = i_s
                    temp_k = k
                    if(temp_k > 0):
                        next_start = i_s

                    while(True):
                        if( temp_i == len(s)-1):
                            if(s[temp_i] != repeat_char and temp_k ==0):
                                temp_i -=1
                            elif (s[temp_i] != repeat_char and temp_k >0):
                                temp_k -=1
                            break
                        if(s[temp_i] == repeat_char ):
                            temp_i += 1
                            continue
                        else:
                            if(temp_k>0):
                                temp_i += 1
                                temp_k -= 1
                            else:
                                break

                    if(temp_i >=len(s)):
                        temp_i = len(s)-1
                    if (len(s) - 1 == temp_i):
                           maximum_distance = max(maximum_distance, temp_i + 1 - start+temp_k)
                    else:
                           maximum_distance = max(maximum_distance, temp_i - start)
                    start = i_s#temp_i#next_start
                    repeat_char = s[i_s]
            if(maximum_distance >len(s)):
                maximum_distance = len(s)

            return maximum_distance

print(Solution.characterReplacement(Solution,s,k))

